server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:knots_db;MODE=MySQL
    username: sa
    password:
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    mode: HTML

# JWT配置
jwt:
  secret: knotsSecretKey2024
  expiration: 86400000 # 24小时

# 文件上传配置
file:
  upload-dir: ./uploads/
